# Generated by Django 4.1.3 on 2022-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('city_name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
